[package]
name = "wind-power"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
circular-queue = "0.2.6"
tabular = "0.2.0"